DROP TABLE IF EXISTS category_mapping;
CREATE TABLE category_mapping (
    org_category varchar,
    new_category  varchar,
    new_memo varchar
);
ALTER TABLE category_mapping OWNER TO postgres;

INSERT INTO category_mapping (org_category, new_category, new_memo)
VALUES
('(blank)','Misc','(blank)'),
('Adjustment','Misc','Adjustment'),
('Auto & Transport','Auto:Transport','Auto & Transport'),
('Auto & Transport:Auto Payment','Auto:Purchase','Auto & Transport:Auto Payment'),
('Bank Chrg','Fees:Bank Chrg','Bank Chrg'),
('Bonus','1090:Income - Bonus','Bonus'),
('Cable','Entertain','Cable'),
('Clothing:AEB - Clothing','Clothing','Clothing:AEB - Clothing'),
('Clothing:ATB - Clothing','Clothing','Clothing:ATB - Clothing'),
('Clothing:clothing','Clothing','Clothing:clothing'),
('Clothing:JGB - Clothing','Clothing','Clothing:JGB - Clothing'),
('Clothing:paxton','Clothing','Clothing:paxton'),
('Clothing:RAB - Clothing','Clothing','Clothing:RAB - Clothing'),
('Credit Card Refund','Fees:Credit Card Refund','Credit Card Refund'),
('Credit Charges','Fees:Credit Charges','Credit Charges'),
('Deferred Compensation','1090:Income - Deferred Compensation','Deferred Compensation'),
('Dell Roth','1090:Roth','Dell Roth'),
('DELL-EMC 401K','1090:401K','DELL-EMC 401K'),
('Dental','1090:Medical - Dental','Dental'),
('EMC Deductions Liberty Mutual','Auto:Insurance','EMC Deductions Liberty Mutual'),
('EMC Deductions:Basic Gtl - EMC','1090:GTL','EMC Deductions:Basic Gtl - EMC'),
('EMC Deductions:HSA','1090:Medical - HSA','EMC Deductions:HSA'),
('EMC Deductions:Ltd - EMC','1090:Long Term Disability','EMC Deductions:Ltd - EMC'),
('EMC Deductions:Medical','1090:Medical','EMC Deductions:Medical'),
('EMC Deductions:Std - EMC','1090:Short Term Disability','EMC Deductions:Std - EMC'),
('Espp Stock','1090:Espp Stock','Espp Stock'),
('Excise','1090:Excise','Excise'),
('Fsa - Med','1090:Medical - FSA','Fsa - Med'),
('Gift Received:Baby Shower','Gifts:Baby Shower','Gift Received:Baby Shower'),
('GTL','1090:GTL','GTL'),
('holiday','Travel:Holiday','holiday'),
('Home Rpair','Household:Home Repair','Home Rpair'),
('HSA Savings','1090:Medical - HSA','HSA Savings'),
('Insp Award Offset','1090:Income - Inspiration Award','Insp Award Offset'),
('Insparation Award','1090:Income - Inspiration Award','Insparation Award'),
('Int Exp','1090:Interest Expenses','Int Exp'),
('Int Inc','1090:Interest Income','Int Inc'),
('Joan's 401K','1090:401K','Joan's 401K'),
('Liberty Mutual','Household:Insurance','Liberty Mutual'),
('MA Paid Family Leave Ins','1090:MA Paid Family Leave Ins','MA Paid Family Leave Ins'),
('MA Paid Medical Leave','1090:MA Paid Medical Leave','MA Paid Medical Leave'),
('Meals Out','Dining','Meals Out'),
('Medical','1090:Medical','Medical'),
('Medical EPO','1090:Medical - EPO','Medical EPO'),
('MNA Stipend','1090:MNA Stipend','MNA Stipend'),
('New House Exps:Building Costs','Household:House Building Costs','New House Exps:Building Costs'),
('Norwood 401K','1090:401K','Norwood 401K'),
('Other Exp','1090:Other Expenses','Other Exp'),
('Other Inc','1090:Income - Other','Other Inc'),
('Parking','Travel:Parking','Parking'),
('Passport','Travel:Passport','Passport'),
('Pension','1090:Income - Pension','Pension'),
('Property Tax','1090:Excise','Property Tax'),
('Rebate - CCards','Fees:Ccards - rebates','Rebate - CCards'),
('Recreation','Entertain','Recreation'),
('Refund','1090:Income - Refund','Refund'),
('Restricted Stk','1090:Restricted Stock','Restricted Stk'),
('Restricted Stock','1090:Restricted Stock','Restricted Stock'),
('Retirement','1090:Income - Retirement','Retirement'),
('Roth Cup','1090:Roth','Roth Cup'),
('Salary - JGB (NEBH)','1090:Income - Salary','Salary - JGB (NEBH)'),
('Salary - JGB (Norwood)','1090:Income - Salary','Salary - JGB (Norwood)'),
('Salary - RAB (EMC)','1090:Income - Salary','Salary - RAB (EMC)'),
('Salary - RAB (EMC):Med - Dental','1090:Medical - Dental','Salary - RAB (EMC):Med - Dental'),
('Salary - RAB (EMC):Vision','1090:Medical - Vision','Salary - RAB (EMC):Vision'),
('Salary Spouse','1090:Income - Salary','Salary Spouse'),
('Social Security','1090:Income - Social Security','Social Security'),
('Stock Rollover Adjustment','1090:Stock Rollover','Stock Rollover Adjustment'),
('Tax - JGB (NEBH)','1090:Income - Salary','Tax - JGB (NEBH)'),
('Tax - JGB (NEBH):Fed - JGB (NEBH)','1090:Federal Tax','Tax - JGB (NEBH):Fed - JGB (NEBH)'),
('Tax - JGB (NEBH):FICA - JGB (NEBH)','1090:FICA Tax','Tax - JGB (NEBH):FICA - JGB (NEBH)'),
('Tax - JGB (NEBH):MCare - JGB (NEBH)','1090:Medicare','Tax - JGB (NEBH):MCare - JGB (NEBH)'),
('Tax - JGB (NEBH):State - JGB (NEBH)','1090:State Tax','Tax - JGB (NEBH):State - JGB (NEBH)'),
('Tax - JGB (Norwood)','1090:Income - Salary','Tax - JGB (Norwood)'),
('Tax - JGB (Norwood):Fed - JGB (Norwood)','1090:Federal Tax','Tax - JGB (Norwood):Fed - JGB (Norwood)'),
('Tax - JGB (Norwood):FICA - JGB (Norwood)','1090:FICA Tax','Tax - JGB (Norwood):FICA - JGB (Norwood)'),
('Tax - JGB (Norwood):MCare - JGB (Norwood)','1090:Medicare','Tax - JGB (Norwood):MCare - JGB (Norwood)'),
('Tax - JGB (Norwood):State - JGB (Norwood)','1090:State Tax','Tax - JGB (Norwood):State - JGB (Norwood)'),
('Tax - RAB (EMC)','1090:Income - Salary','Tax - RAB (EMC)'),
('Tax - RAB (EMC):Fed - RAB 4','1090:Federal Tax','Tax - RAB (EMC):Fed - RAB 4'),
('Tax - RAB (EMC):FICA - RAB 4','1090:FICA Tax','Tax - RAB (EMC):FICA - RAB 4'),
('Tax - RAB (EMC):MCare - RAB 4','1090:Medicare','Tax - RAB (EMC):MCare - RAB 4'),
('Tax - RAB (EMC):MCare - Surtax','1090:Medicare surtax','Tax - RAB (EMC):MCare - Surtax'),
('Tax - RAB (EMC):State - RAB 4','1090:State Tax','Tax - RAB (EMC):State - RAB 4'),
('Tax -Rebate','1090:Income - Tax Rebate','Tax -Rebate'),
('Tax -Rebate:Tax Rebate','1090:Income - Tax Rebate','Tax -Rebate:Tax Rebate'),
('Tax Spouse','1090:Income - Other','Tax Spouse'),
('Tax Spouse:Fed','1090:Federal Tax','Tax Spouse:Fed'),
('Tax Spouse:Medicare','1090:Medicare','Tax Spouse:Medicare'),
('Tax Spouse:Other','1090:Income - Other','Tax Spouse:Other'),
('Tax Spouse:State','1090:State Tax','Tax Spouse:State'),
('Unallocated','Misc','Unallocated'),
('Wedding','Gits:Wedding','Wedding'),
('Working Spouse Contribution','1090:Working Spouse Contribution','Working Spouse Contribution'),
('Xmas','Gifts:Xmas','Xmas'),
('_DivInc','1090:_DivInc',''),
('_IntInc','1090:_IntInc',''),
('_RlzdGain','1090:_RlzdGain',''),
('account fee','Fees:account fee',''),
('Christmas','Gifts:Xmas',''),
('Insurance','Household:Insurance','');

