{
 "title": "CD Ladder",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CD Ladder",
   "type": "table",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT end_date::text, term, rate, value, deposit, increase, bank, start_date::text, name FROM cd_ladder LIMIT 50 "
    }
   ]
  },
  {
   "title": "Initial Value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(deposit)::text FROM cd_ladder LIMIT 50 "
    }
   ]
  },
  {
   "title": "Current Value",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(value)::text FROM cd_ladder LIMIT 50 "
    }
   ]
  },
  {
   "title": "Gains",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(increase)::text || '  (' || (SUM(increase) * 100./ SUM(deposit))::numeric(4,2)::text || '%)' as inf FROM cd_ladder LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of CD's",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Count(*)::text  as inf FROM cd_ladder LIMIT 50 "
    }
   ]
  }
 ]
}