{
 "title": "Financial Summary",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "next_cd",
    "query": "SELECT value || ': ' || substring(info FROM 22) AS info FROM summary WHERE id = 1 ORDER BY id LIMIT 1"
   }
  ]
 },
 "panels": [
  { "title": "Ballantyne Finances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Net Worth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT net_worth FROM aggreg_info LIMIT 300\r\n"
    }
   ]
  },
  {
   "title": "US Cash Assets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cash_assets FROM aggreg_info LIMIT 300"
    }
   ]
  },
  { "title": "Next CD to mature", "type": "text", "gridPos": { "h": 4, "w": 12, "x": 8, "y": 1 }, "options": { "content": "##### ${next_cd}" } },
  {
   "title": "Wealth Summary",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT info, value FROM summary WHERE id not in (0,15,16,17,18,19) ORDER BY id LIMIT 300"
    }
   ]
  },
  {
   "title": "Wealth",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT datetime as \"time\", managed_funds AS \"Managed Funds\" FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    },
    {
     "rawSql": "SELECT datetime as \"time\", cash_assets as \"US Cash Assets\" FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    },
    {
     "dataset": "money",
     "rawSql": "SELECT datetime as \"time\", uk_assets AS \"UK assets\" FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    }
   ]
  },
  {
   "title": "Managed Funds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT datetime as \"time\", annuities FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    },
    {
     "rawSql": "SELECT datetime as \"time\", jgb_401k AS \"JGB: 401K\" FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    },
    {
     "rawSql": "SELECT datetime as \"time\", rab_401k AS \"RAB: 401K\" FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    },
    {
     "rawSql": "SELECT datetime as \"time\", roth_ira AS \"Roth IRA\" FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    }
   ]
  },
  {
   "title": "US Cash Assets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT datetime as \"time\", checking as \"Checking\" FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    },
    {
     "rawSql": "SELECT datetime as \"time\", deferred_comp AS \"Deferred Comp\" FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    },
    {
     "rawSql": "SELECT datetime as \"time\", money_market AS \"Money Market\" FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    },
    {
     "rawSql": "SELECT datetime as \"time\", savings FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    },
    {
     "rawSql": "SELECT datetime as \"time\", cds AS \"CD's\" FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    }
   ]
  },
  {
   "title": "Credit Card Debt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT datetime as \"time\", credit_card_debt AS \"Credit Card Debt\" FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    }
   ]
  },
  {
   "title": "Changes in Net Worth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT datetime as \"time\", weekly_change AS \"Weekly Change\" FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    }
   ]
  },
  {
   "title": "Generational Wealth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "money",
     "rawSql": "SELECT datetime as \"time\", stock as \"Dell Stock\" FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    },
    {
     "dataset": "money",
     "rawSql": "SELECT datetime as \"time\", property as \"Property\" FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    }
   ]
  },
  {
   "title": "Donor Advised Fund",
   "type": "timeseries",
   "description": "account for charitable giving",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT datetime as \"time\", charitable_fund AS \"Donor Fund\" FROM aggreg_info WHERE $__timeFilter(datetime) ORDER BY datetime LIMIT 300"
    }
   ]
  },
  { "title": "Market", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Market Indices",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH A AS (\r\n  SELECT datetime, nasdaq,\r\n         FIRST_VALUE(nasdaq) OVER (ORDER BY datetime) AS base\r\n  FROM aggreg_info\r\n  WHERE $__timeFilter(datetime)\r\n)\r\nSELECT datetime AS \"time\",\r\n       (nasdaq / base) * 100 AS \"NASDAQ\"\r\nFROM A\r\nORDER BY datetime\r\nLIMIT 300"
    },
    {
     "rawSql": "WITH B AS (\r\n  SELECT datetime, snp,\r\n         FIRST_VALUE(snp) OVER (ORDER BY datetime) AS base\r\n  FROM aggreg_info\r\n  WHERE $__timeFilter(datetime)\r\n)\r\nSELECT datetime AS \"time\",\r\n       (snp / base) * 100 AS \"S&P 500\"\r\nFROM B\r\nORDER BY datetime\r\nLIMIT 300"
    },
    {
     "rawSql": "WITH C AS (\r\n  SELECT datetime, dji,\r\n         FIRST_VALUE(dji) OVER (ORDER BY datetime) AS base\r\n  FROM aggreg_info\r\n  WHERE $__timeFilter(datetime)\r\n)\r\nSELECT datetime AS \"time\",\r\n       (dji / base) * 100 AS \"Dow Jones Industrial\"\r\nFROM C\r\nORDER BY datetime\r\nLIMIT 300"
    },
    {
     "rawSql": "WITH D AS (\r\n  SELECT datetime, barnum_fg,\r\n         FIRST_VALUE(barnum_fg) OVER (ORDER BY datetime) AS base\r\n  FROM aggreg_info\r\n  WHERE $__timeFilter(datetime)\r\n)\r\nSELECT datetime AS \"time\",\r\n       (barnum_fg / base) * 100 AS \"Barnum Holdings\"\r\nFROM D\r\nORDER BY datetime\r\nLIMIT 300"
    },
    {
     "rawSql": "WITH E AS (\r\n  SELECT datetime, net_worth,\r\n         FIRST_VALUE(net_worth) OVER (ORDER BY datetime) AS base\r\n  FROM aggreg_info\r\n  WHERE $__timeFilter(datetime)\r\n)\r\nSELECT datetime AS \"time\",\r\n       (net_worth / base) * 100 AS \"Net Worth\"\r\nFROM E\r\nORDER BY datetime\r\nLIMIT 300"
    }
   ]
  }
 ]
}