{
 "title": "Travel Summary",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Travel",
   "type": "table",
   "gridPos": { "h": 17, "w": 11, "x": 0, "y": 1 },
   "targets": [
    { "dataset": "money", "rawSql": "SELECT * FROM travel" }
   ]
  },
  {
   "title": "Year over year - Monthly income",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 9, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "money",
     "rawSql": "SELECT end_of_month as \"time\", amount::numeric, \"year-1\"::numeric, \"year-2\"::numeric FROM monthly_income WHERE $__timeFilter(end_of_month) ORDER BY end_of_month LIMIT 12"
    }
   ]
  },
  {
   "title": "Annual Income",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 8, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "money",
     "rawSql": "select year, amount::numeric from annual_income"
    }
   ]
  }
 ]
}