{
 "title": "kafka core overview",
 "description": "kafka core metrics overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kafka_server_kafkaServer_BrokerState, for)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(kafka_server_kafkaServer_BrokerState{for=~\"$cluster\"},host)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka_topic_partition{for=~\"$cluster\"},topic)"
    }
   },
   {
    "name": "consumergroup",
    "label": "consumergroup",
    "query": {
     "query": "label_values(kafka_consumergroup_lag_new{for=~\"$cluster\"},consumergroup)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "kafka cluster related monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Number of brokers in the kafka cluster",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_kafkaServer_BrokerState{for=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "kafka total stack count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag_new{for=\"$cluster\"})",
     "legendFormat": "Total accumulation of clusters"
    }
   ]
  },
  {
   "title": "Number of partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_PartitionCount{for=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number of kafka topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_topic_partition{for=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number of Partitions without Leader",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_controller_OfflinePartitionsCount{for=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number of Active Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_ActiveControllerCount{for=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "ISR expansion rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_ReplicaManager_IsrExpandsPerSec_count{for=\"$cluster\"})[2m])"
    }
   ]
  },
  {
   "title": "ISR shrink rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_ReplicaManager_IsrShrinksPerSec_count{for=\"$cluster\"})[2m])"
    }
   ]
  },
  {
   "title": "kafka cluster message production rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_MessagesInPerSec{for=\"$cluster\"}))",
     "legendFormat": "Cluster message production rate"
    }
   ]
  },
  {
   "title": "kafka writes topic messages per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_MessagesInPerSecPerTopic{for=\"$cluster\",rate=\"Count\"}))",
     "legendFormat": "{{topic}} -{{host}} number of topics written per second"
    }
   ]
  },
  {
   "title": "kafka sends unconsumed time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "min(kafka_consumergroup_delaytime{for=\"$cluster\"}) by (consumergroup,topic)",
     "legendFormat": "Consumer group:{{consumergroup}} - topic:{{topic}}"
    }
   ]
  },
  {
   "title": "kafka stacking situation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag_new{for=\"$cluster\"}) by (consumergroup,topic)",
     "legendFormat": "Consumer group:{{consumergroup}} - topic:{{topic}}"
    }
   ]
  },
  {
   "title": "kafka cluster writes bytes per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_BytesInPerSec{for=\"$cluster\",rate=\"Count\"}))",
     "legendFormat": "{{host}} writes bytes per second"
    }
   ]
  },
  {
   "title": "kafka writes topic bytes per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_BytesInPerSecPerTopic{for=\"$cluster\",rate=\"Count\"}))",
     "legendFormat": "{{topic}} -{{host}} writes topic bytes per second"
    }
   ]
  },
  {
   "title": "kafka cluster reads bytes per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_BytesOutPerSec{for=\"$cluster\",rate=\"Count\"}))",
     "legendFormat": "{{host}} read bytes per second"
    }
   ]
  },
  {
   "title": "kafka reads topic bytes per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_BytesOutPerSecPerTopic{for=\"$cluster\",rate=\"Count\"}))",
     "legendFormat": "{{topic}} -{{host}} reads topic bytes per second"
    }
   ]
  },
  {
   "title": "High-level monitoring of kafka cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Handler Thread Idleness",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_kafkaRequestHandlerPoolRequestHandlerAvgIdlePercent{rate=\"OneMinuteRate\",for=\"$cluster\"}",
       "legendFormat": "{{host}}: request handler thread idle condition"
      }
     ]
    },
    {
     "title": "Response queue size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 9, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_RequestChannelResponseQueueSize{for=\"$cluster\"})",
       "legendFormat": "Response queue size"
      }
     ]
    },
    {
     "title": "Size of the request queue",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_RequestChannelRequestQueueSize{for=\"$cluster\"})",
       "legendFormat": "Size of the request queue"
      }
     ]
    },
    {
     "title": "NetworkProcessorAvgIdlePercent",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_network_SocketServer_NetworkProcessorAvgIdlePercent{for=\"$cluster\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "ReplicaManager_IsrShrinksPerSec_count ISR shrinks per second",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_server_ReplicaManager_IsrShrinksPerSec_count{for=\"$cluster\"}[2m]))"
      }
     ]
    },
    {
     "title": "ReplicaManager_IsrExpandsPerSec_count ISR expansions per second",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_server_ReplicaManager_IsrExpandsPerSec_count{for=\"$cluster\"}[2m]))"
      }
     ]
    },
    {
     "title": "Under Replicated Partitionis",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_ReplicaManager_UnderReplicatedPartitions{for=\"$cluster\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "LogFlushStats_LogFlushRateAndTimeMs_Count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(kafka_log_LogFlushStats_LogFlushRateAndTimeMs_count{for=\"$cluster\"}[2m])",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "LogFlushStats_LogFlushRateAndTimeMs(TP99)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_log_LogFlushStats_LogFlushRateAndTimeMs{for=\"$cluster\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "kafkaRequestHandlerPool_RequestHandlerAvgIdlePercent",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "irate(kafka_server_kafkaRequestHandlerPool_RequestHandlerAvgIdlePercent_count{for=\"$cluster\"}[2m])",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "zk related monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "zk cluster status",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(zk_up{job=\"ck-zk-olap\"}) != bool 3 or absent(sum(zk_up{job=\"ck-zk-olap\"}) != bool 3)"
      }
     ]
    },
    {
     "title": "zk node type",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 2, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "zk_server_leader{job=~\"ck-zk-olap\"}",
       "legendFormat": "{{zk_host}}"
      }
     ]
    },
    {
     "title": "zk processing latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(zk_min_latency{job=~\"ck-zk-olap\"})",
       "legendFormat": "Zk processing minimum delay"
      },
      {
       "expr": "max(zk_max_latency{job=~\"ck-zk-olap\"})",
       "legendFormat": "zk processing max delay"
      },
      {
       "expr": "max(zk_avg_latency{job=~\"ck-zk-olap\"})",
       "legendFormat": "zk processing average delay"
      }
     ]
    },
    {
     "title": "zk storage data volume",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "zk_approximate_data_size{job=~\"ck-zk-olap\"}",
       "legendFormat": "Stored data for {{zk_host}}"
      }
     ]
    },
    {
     "title": "Number of watches for zk",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_watch_count{job=\"ck-zk-olap\"}",
       "legendFormat": "{{zk_host}} node watch count"
      }
     ]
    }
   ]
  },
  {
   "title": "kafka Topic, ConsumerGroup monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "topic stacking number",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag_new{for=\"$cluster\",topic=\"$topic\",consumergroup=~\"$consumergroup\"})",
     "legendFormat": "{{$topic}} accumulation number"
    }
   ]
  },
  {
   "title": "Number of partitions",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 10, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition{for=\"$cluster\",topic=\"$topic\"}"
    }
   ]
  },
  {
   "title": "kafka writes topic messages per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_MessagesInPerSecPerTopic{for=\"$cluster\",rate=\"Count\",topic=\"$topic\",host=~\"$host\"}))",
     "legendFormat": "{{topic}} -{{host}} number of topics written per second"
    }
   ]
  },
  {
   "title": "kafka topic sends unconsumed time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "min(kafka_consumergroup_delaytime{for=\"$cluster\",topic=\"$topic\",consumergroup=~\"$consumergroup\"}) by (consumergroup,topic)",
     "legendFormat": "Consumer group:{{consumergroup}} - topic:{{topic}}"
    }
   ]
  },
  {
   "title": "kafka topic accumulation",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag_new{for=\"$cluster\",topic=\"$topic\",consumergroup=~\"$consumergroup\"}) by (consumergroup,topic)",
     "legendFormat": "Consumer group:{{consumergroup}} - topic:{{topic}}"
    }
   ]
  },
  {
   "title": "kafka writes topic bytes per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_BytesInPerSecPerTopic{for=\"$cluster\",rate=\"Count\",topic=\"$topic\",host=~\"$host\"}))",
     "legendFormat": "{{topic}} -{{host}} writes topic bytes per second"
    }
   ]
  },
  {
   "title": "kafka reads topic bytes per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_BytesOutPerSecPerTopic{for=\"$cluster\",rate=\"Count\",topic=\"$topic\",host=~\"$host\"}))",
     "legendFormat": "{{topic}} -{{host}} reads topic bytes per second"
    }
   ]
  },
  {
   "title": "kafka cluster JVM monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "kafka_Runtime_Uptime",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_Runtime_Uptime{for=\"$cluster\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "kafka_Threading_ThreadCount",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_Threading_ThreadCount{for=\"$cluster\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "GarbageCollector_G1_Young_Generation_CollectionTime",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_jvm_GarbageCollector_G1_Young_Generation_CollectionTime{for=\"$cluster\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "GarbageCollector_G1_Old_Generation_CollectionCount",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_jvm_GarbageCollector_G1_Old_Generation_CollectionCount{for=\"$cluster\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Memory_HeapMemoryUsage_used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_jvm_Memory_HeapMemoryUsage_used{for=\"$cluster\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "MemoryPool_G1_Survivor_Space_used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_jvm_MemoryPool_G1_Survivor_Space_used{for=\"$cluster\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "MemoryPool_G1_Eden_Space_used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_jvm_MemoryPool_G1_Eden_Space_used{for=\"$cluster\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "GarbageCollector_G1_Young_Generation_CollectionCount",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_jvm_GarbageCollector_G1_Young_Generation_CollectionCount{for=\"$cluster\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "MemoryPool_G1_Old_Gen_used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_jvm_MemoryPool_G1_Old_Gen_used{for=\"$cluster\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "GarbageCollector_G1_Old_Generation_CollectionTime",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_jvm_GarbageCollector_G1_Old_Generation_CollectionTime{for=\"$cluster\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "kafka_OperatingSystem_FreePhysicalMemorySize",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_OperatingSystem_FreePhysicalMemorySize{for=\"$cluster\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "kafka_OperatingSystem_OpenFileDescriptorCount",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_OperatingSystem_OpenFileDescriptorCount{for=\"$cluster\"}",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  }
 ]
}